---
- name: 'Ensure libssl-dev'
  apt: name=libssl-dev

- name: 'Download stunnel {{ stunnel.version }}'
  get_url: >
    url="https://www.stunnel.org/downloads/stunnel-{{ stunnel.version }}.tar.gz"
    dest="/usr/src/stunnel-{{ stunnel.version }}.tar.gz"

- name: 'Compile stunnel'
  shell: |
    set -e
    cd /usr/src
    test -d "stunnel-{{ stunnel.version }}" && rm -r "stunnel-{{ stunnel.version }}"
    tar zxf "stunnel-{{ stunnel.version }}.tar.gz"
    cd "stunnel-{{ stunnel.version }}"
    ./configure && make
    cp src/stunnel "/usr/bin/stunnel5-{{ stunnel.version }}.bin"

    test -L "/usr/bin/stunnel4" || mv "/usr/bin/stunnel4" "/usr/bin/stunnel4-4.53"
    test -L "/usr/bin/stunnel4" && rm "/usr/bin/stunnel4"

    ln -s "/usr/bin/stunnel5-{{ stunnel.version }}.bin" /usr/bin/stunnel4
    ln -s "/usr/bin/stunnel5-{{ stunnel.version }}.bin" "/usr/bin/stunnel5-{{ stunnel.version }}"
  args:
    creates: "/usr/bin/stunnel5-{{ stunnel.version }}"
  notify:
    - 'ensure stunnel chroot dir'
    - 'enable stunnel4'
